-- Content Library table for Uburn Cockpit
-- Stores all content generated by agents or uploaded manually

CREATE TABLE IF NOT EXISTS content_library (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  type text NOT NULL DEFAULT 'instagram_post',
  status text NOT NULL DEFAULT 'draft',
  title text DEFAULT '',
  caption text DEFAULT '',
  hook text DEFAULT '',
  cta text DEFAULT '',
  hashtags text[] DEFAULT '{}',
  image_url text,
  video_url text,
  platform text DEFAULT 'instagram',
  format text DEFAULT 'feed',
  ai_suggestions jsonb,
  source text DEFAULT 'manual',
  agent_name text,
  best_time text,
  priority text DEFAULT 'medium',
  meta_post_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  published_at timestamptz
);

-- Index for fast filtering
CREATE INDEX IF NOT EXISTS idx_content_type ON content_library(type);
CREATE INDEX IF NOT EXISTS idx_content_status ON content_library(status);
CREATE INDEX IF NOT EXISTS idx_content_created ON content_library(created_at DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE content_library ENABLE ROW LEVEL SECURITY;

-- Allow all operations for service role
CREATE POLICY "Service role full access" ON content_library
  FOR ALL
  USING (true)
  WITH CHECK (true);
